# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
import time

s = Service('C:/Users/User/Downloads/chromedriver_win32/chromedriver.exe')
driver = webdriver.Chrome(service=s)
driver.get(
    "https://idemo.bspb.ru/auth?response_type=code&client_id=1&redirect_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fsuccess&prefetch_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fprefetch&force_new_session=true")
driver.set_window_size(1366, 768)

driver.find_element(By.ID, "login-button").click()
driver.find_element(By.ID, "login-otp-button").click()
driver.find_element(By.ID, "accounts").click()
driver.find_element(By.XPATH, "/html/body/div[2]/div/div[2]/div[2]/div[3]/table/tbody/tr[3]/td[1]/a").click()
time.sleep(2)
driver.find_element(By.ID, "payments-form").click()
driver.find_element(By.ID, "personal-payment").click()
driver.find_element(By.ID, "amount").send_keys("1000")
time.sleep(1)
driver.find_element(By.XPATH, "//*[@id='personal-payment-form']/div[4]/button[2]").click()
time.sleep(3)
driver.close()

