# Generated by Selenium IDE


  

    driver.find_element(By.ID, "login-button").click()
    driver.find_element(By.ID, "login-otp-button").click()
    driver.find_element(By.ID, "accounts-index").click()
    driver.find_element(By.ID, "account-10039").click()
    driver.find_element(By.ID, "statements-statement").click()
    driver.find_element(By.CSS_SELECTOR, "#until-date .icon-calendar").click()
    driver.find_element(By.CSS_SELECTOR, ".datepicker:nth-child(28) tr:nth-child(3) > .day:nth-child(3)").click()
    driver.find_element(By.ID, "query-button").click()
    driver.find_element(By.CSS_SELECTOR, ".icon-close").click()
    time.sleep(3)
  
